pub const MAX_BLOCK_SIZE:usize = 1000000;
pub const MAX_BLOCK_SIGOPS:usize = MAX_BLOCK_SIZE/50;
pub const COINBASE_MATURITY:usize = 100;

pub use self::error::{GenericError, Error};
pub use self::uint256::{UInt256, ParseUInt256Error};
pub use self::consensus_params::ConsensusParams;
pub use self::chain_params::ChainParams;
pub use self::block::Block;
pub use self::block_header::BlockHeader;
pub use self::block_locator::BlockLocator;
pub use self::merkle_block::MerkleBlock;
pub use self::merkle_tree::PartialMerkleTree;
pub use self::transaction::TxIn;
pub use self::transaction::TxOut;
pub use self::transaction::OutPoint;
pub use self::transaction::Amount;
pub use self::transaction::Transaction;
pub use self::pubkey::PubKey;

pub mod error;
pub mod uint256;
pub mod hasher;
pub mod pubkey;
pub mod consensus_params;
pub mod chain_params;
pub mod pow;
pub mod transaction;
pub mod merkle_tree;
pub mod merkle_block;
pub mod block_header;
pub mod block_locator;
pub mod block;
